import React from "react";
import styles from "./Terms&Privacy.module.css";

interface TermsModalProps {
  isOpen: boolean;
  onClose: () => void;
  type: "privacy" | "terms";
}

const TermsModal: React.FC<TermsModalProps> = ({ isOpen, onClose, type }) => {
  if (!isOpen) return null;

  const termsContent = (
    <div className={styles.sections}>
      <section className={styles.section}>
        <p>Effective Date: January 4, 2025</p>
        <p>
          Welcome to CashMap. These Terms of Service ("Terms") govern your
          access to and use of our services. By using CashMap, you agree to
          these Terms and our Privacy Policy. If you do not agree, please
          refrain from using our services.
        </p>
      </section>
      <section className={styles.section}>
        <h3>1. Acceptance of Terms</h3>
        <p>
          By accessing or using CashMap, you confirm that you accept these Terms
          and agree to be bound by them.
        </p>
      </section>
      <section className={styles.section}>
        <h3>2. About CashMap</h3>
        <p>
          CashMap provides tools to help users manage their personal finances,
          offering:
        </p>
        <ul>
          <li>Summaries of financial transactions.</li>
          <li>Analytical statistics on income and expenses.</li>
          <li>Predictive insights derived from user-provided data.</li>
        </ul>
        <p>
          CashMap is not a financial advisor and does not provide financial,
          tax, or legal advice.
        </p>
      </section>
      <section className={styles.section}>
        <h3>3. Eligibility</h3>
        <p>You must be at least 18 years old to use CashMap.</p>
        <p>
          By using CashMap, you affirm that all information provided is
          accurate, complete, and up-to-date.
        </p>
        <p>The service is subject to the laws of Lima, Peru.</p>
      </section>
      <section className={styles.section}>
        <h3>4. User Responsibilities</h3>
        <p>Maintain the confidentiality of your account credentials.</p>
        <p>Do not use CashMap for unlawful or unauthorized purposes.</p>
        <p>
          Avoid attempting to reverse-engineer, disrupt, or exploit the platform
          in any unauthorized manner.
        </p>
      </section>
      <section className={styles.section}>
        <h3>5. Service Limitations</h3>
        <p>
          Predictions and insights generated by CashMap are estimates and not
          guaranteed to be accurate or reliable.
        </p>
        <p>
          CashMap may experience interruptions or technical issues beyond its
          control.
        </p>
      </section>
      <section className={styles.section}>
        <h3>6. Privacy and Data Protection</h3>
        <p>
          Your personal data will be handled in accordance with our Privacy
          Policy.
        </p>
        <p>
          CashMap complies with Peru’s Personal Data Protection Law (Law No.
          29733).
        </p>
      </section>
      <section className={styles.section}>
        <h3>7. Intellectual Property</h3>
        <p>
          All materials, including software, designs, and trademarks, are the
          exclusive property of CashMap.
        </p>
        <p>
          You may not copy, modify, or distribute CashMap’s materials without
          prior written consent.
        </p>
      </section>
      <section className={styles.section}>
        <h3>8. Modifications to the Terms</h3>
        <p>
          CashMap reserves the right to update these Terms at any time. Changes
          will be communicated via the website or email. Continued use of the
          service constitutes acceptance of any revisions.
        </p>
      </section>
      <section className={styles.section}>
        <h3>9. Limitation of Liability</h3>
        <p>
          CashMap is provided "as is" without warranties of any kind. We are not
          liable for any direct, indirect, incidental, or consequential damages
          arising from your use of the service.
        </p>
      </section>
      <section className={styles.section}>
        <h3>10. Governing Law and Jurisdiction</h3>
        <p>
          These Terms are governed by the laws of the Republic of Peru. Any
          disputes will be resolved exclusively in the courts of Lima, Peru.
        </p>
      </section>
      <section className={styles.section}>
        <h3>11. Contact Information</h3>
        <p>If you have questions about these Terms, please contact us at:</p>
        <p>
          Email: <a href="mailto:CashMap@gmail.com">CashMap@gmail.com</a>
        </p>
      </section>
    </div>
  );

  const privacyContent = (
    <div className={styles.sections}>
      <section className={styles.section}>
        <p>Effective Date: January 4, 2025</p>
        <p>
          At CashMap, we are committed to protecting your privacy. This Privacy
          Policy explains how we collect, use, store, and share your information
          when you use our services.
        </p>
      </section>
      <section className={styles.section}>
        <h3>1. Information We Collect</h3>
        <ul>
          <li>
            Personal Information: Name, email address, financial data (e.g.,
            income, expenses).
          </li>
          <li>
            Non-Personal Information: Usage data, device information (e.g., IP
            address, browser type).
          </li>
        </ul>
      </section>
      <section className={styles.section}>
        <h3>2. How We Use Your Information</h3>
        <ul>
          <li>Provide and improve our services.</li>
          <li>Generate financial insights and predictions.</li>
          <li>Personalize your experience.</li>
          <li>Communicate important updates or changes.</li>
        </ul>
      </section>
      <section className={styles.section}>
        <h3>3. Data Sharing</h3>
        <p>We do not sell or rent your data. We may share information:</p>
        <ul>
          <li>With service providers for operational purposes.</li>
          <li>To comply with legal obligations.</li>
          <li>During business transactions (e.g., mergers or acquisitions).</li>
        </ul>
      </section>
      <section className={styles.section}>
        <h3>4. Data Security</h3>
        <p>
          We use encryption, secure storage, and regular audits to protect your
          data. However, no system is entirely secure. You acknowledge the
          inherent risks of online data transmission.
        </p>
      </section>
      <section className={styles.section}>
        <h3>5. Your Rights</h3>
        <p>
          Under Peru’s Personal Data Protection Law (Law No. 29733), you may:
        </p>
        <ul>
          <li>Access your data.</li>
          <li>Request corrections.</li>
          <li>Request deletion, subject to legal obligations.</li>
        </ul>
        <p>
          To exercise these rights, contact us at{" "}
          <a href="mailto:CashMap@gmail.com">CashMap@gmail.com</a>.
        </p>
      </section>
      <section className={styles.section}>
        <h3>6. Data Retention</h3>
        <p>
          Your data is retained only as long as necessary for operational or
          legal purposes.
        </p>
      </section>
      <section className={styles.section}>
        <h3>7. Cookies</h3>
        <p>
          CashMap uses cookies to enhance your experience. You can manage cookie
          preferences via your browser settings.
        </p>
      </section>
      <section className={styles.section}>
        <h3>8. Third-Party Links</h3>
        <p>
          We are not responsible for the privacy practices of third-party
          websites linked through our platform.
        </p>
      </section>
      <section className={styles.section}>
        <h3>9. Changes to This Policy</h3>
        <p>
          We may update this Privacy Policy as needed. Changes will be
          communicated through our website or email.
        </p>
      </section>
      <section className={styles.section}>
        <h3>10. Contact Information</h3>
        <p>
          If you have questions about this Privacy Policy, please contact us:
        </p>
        <p>
          Email: <a href="mailto:CashMap@gmail.com">CashMap@gmail.com</a>
        </p>
      </section>
    </div>
  );

  return (
    <>
      <div className={styles.overlay} onClick={onClose} />
      <div className={styles.container}>
        <div className={styles.header}>
          <h2>{type === "privacy" ? "Privacy Policy" : "Terms of Service"}</h2>
          <button className={styles.closeButton} onClick={onClose}>
            ×
          </button>
        </div>
        <div className={styles.content}>
          {type === "privacy" ? privacyContent : termsContent}
        </div>
      </div>
    </>
  );
};

export default TermsModal;
